#!/usr/bin/env bash
# wrapper with --fakeroot
if [[ -z "${CAUR_PACMAN_SYNC}" ]]; then
    CAUR_PACMAN_SYNC="${HOME}/chaotic/pacman-sync"
fi
install -o"$(whoami)" -dDm755 "${CAUR_PACMAN_SYNC}"

exec singularity --silent exec --fakeroot \
    -B "${CAUR_PACMAN_SYNC}":/var/lib/pacman/sync \
    docker://quay.io/chaotic/toolbox-deps \
    /tini -s -- "$(basename "$0")" "$@"
