#!/usr/bin/env bash
# wrapper without --fakeroot
if [[ -z "${CAUR_PACMAN_SYNC}" ]]; then
    CAUR_PACMAN_SYNC="${HOME}/chaotic/pacman-sync"
fi
install -o"$(whoami)" -dDm755 "${CAUR_PACMAN_SYNC}"

exec tini -s -- singularity --silent exec \
    -B "${CAUR_PACMAN_SYNC}":/var/lib/pacman/sync \
    docker://quay.io/chaotic/toolbox-deps \
    "$(basename "$0")" "$@"
