#!/usr/bin/env bash
CAUR_LOWER_DIR='/var/cache/chaotic/lower'
CAUR_LOWER_PKGS='base base-devel'
CAUR_GUEST_USER='main-builder'
CAUR_GUEST_UID=1000
CAUR_GUEST_ETC='/usr/lib/chaotic/guest/etc'
CAUR_GUEST_BIN='/usr/lib/chaotic/guest/bin'
CAUR_GUEST_GNUPG='/var/lib/chaotic/gnupg'

if [ "$EUID" -ne 0 ]; then
    echo 'This script must be run as root.'
    exit -1
fi

source lib/*
$@